#!/usr/bin/env bash
# This Bash script pings an IP address passed as an argument. Requirements: Accepts a string as an argument. Displays Usage: 5-is_the_host_on_the_network {IP_ADDRESS} if no argument passed. Ping the IP 5 times

ifconfig | grep -Eo "inet (addr:)?([0-9]*\.){3}[0-9]*" | cut -b 11-
